# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-15 14:46:02
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def MSolarFarmSuitability():  # Model_

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("3D")

    arcpy.ImportToolbox(r"c:\users\dell\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\GeoAnalytics Desktop Tools.tbx")
    electrical_grid = "electrical_grid"
    study_area_2_ = "study_area"
    gis_osm_roads_free_1 = "gis_osm_roads_free_1"
    study_area = "study_area"
    protectedarea = "protectedarea"
    PVOUT_tif_2_ = arcpy.Raster("PVOUT.tif")
    output_SRTMGL3_tif = arcpy.Raster("output_SRTMGL3.tif")
    LandCover_tif = arcpy.Raster("LandCover.tif")

    # Process: Clip Layer (2) (Clip Layer) (gapro)
    grid = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\grid"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
        arcpy.gapro.ClipLayer(input_layer=electrical_grid, clip_layer=study_area_2_, out_feature_class=grid)

    # Process: Distance Accumulation (Distance Accumulation) (sa)
    Gird_Proximity = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Gird_Proximity"
    Distance_Accumulation = Gird_Proximity
    Output_Back_Direction_Raster = ""
    Output_Source_Direction_Raster = ""
    Output_Source_Location_Raster = ""
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
        Gird_Proximity = arcpy.sa.DistanceAccumulation(grid, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster, Output_Source_Direction_Raster, Output_Source_Location_Raster, "", "", "", "", "PLANAR")
        Gird_Proximity.save(Distance_Accumulation)


    # Process: Clip Layer (Clip Layer) (gapro)
    Road_shp = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Road.shp"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
        arcpy.gapro.ClipLayer(input_layer=gis_osm_roads_free_1, clip_layer=study_area, out_feature_class=Road_shp)

    # Process: Distance Accumulation (2) (Distance Accumulation) (sa)
    Road_Proximity = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Road_Proximity"
    Distance_Accumulation_2_ = Road_Proximity
    Output_Back_Direction_Raster_2_ = ""
    Output_Source_Direction_Raster_2_ = ""
    Output_Source_Location_Raster_2_ = ""
    Road_Proximity = arcpy.sa.DistanceAccumulation(Road_shp, "", "", "", "", "BINARY 1 -30 30", "", "BINARY 1 45", Output_Back_Direction_Raster_2_, Output_Source_Direction_Raster_2_, Output_Source_Location_Raster_2_, "", "", "", "", "PLANAR")
    Road_Proximity.save(Distance_Accumulation_2_)


    # Process: Pairwise Clip (Pairwise Clip) (analysis)
    protectedarea_Clip = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\protectedarea_Clip"
    arcpy.analysis.PairwiseClip(in_features=protectedarea, clip_features=study_area, out_feature_class=protectedarea_Clip)

    # Process: Clip Raster (2) (Clip Raster) (management)
    PVOUT_Clip = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\PVOUT_Clip"
    arcpy.management.Clip(in_raster=PVOUT_tif_2_, rectangle="7.675170900328 10.5433585001296 9.36031150289369 12.6046040000753", out_raster=PVOUT_Clip, in_template_dataset=study_area_2_, clipping_geometry="ClippingGeometry")
    PVOUT_Clip = arcpy.Raster(PVOUT_Clip)

    # Process: Project Raster (2) (Project Raster) (management)
    Projected_SolarPV = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Projected_SolarPV"
    arcpy.management.ProjectRaster(in_raster=PVOUT_Clip, out_raster=Projected_SolarPV, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", cell_size="10 10")
    Projected_SolarPV = arcpy.Raster(Projected_SolarPV)

    # Process: Reclassify (Reclassify) (sa)
    Reclass_SolarPV = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_SolarPV"
    Reclassify = Reclass_SolarPV
    Reclass_SolarPV = arcpy.sa.Reclassify(Projected_SolarPV, "VALUE", "4.609000 4.664659 1;4.664659 4.692824 2;4.692824 4.712941 3;4.712941 4.739094 4;4.739094 4.780000 5", "DATA")
    Reclass_SolarPV.save(Reclassify)


    # Process: Fill (Fill) (sa)
    Fill_DEM = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Fill_DEM"
    Fill = Fill_DEM
    Fill_DEM = arcpy.sa.Fill(output_SRTMGL3_tif, None)
    Fill_DEM.save(Fill)


    # Process: Clip Raster (Clip Raster) (management)
    DEM = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\DEM"
    with arcpy.EnvManager(outputCoordinateSystem="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]]"):
        arcpy.management.Clip(in_raster=Fill_DEM, rectangle="7.675170900328 10.5433585001296 9.36031150289369 12.6046040000753", out_raster=DEM, in_template_dataset=study_area, nodata_value="0", clipping_geometry="ClippingGeometry", maintain_clipping_extent="NO_MAINTAIN_EXTENT")
        DEM = arcpy.Raster(DEM)

    # Process: Project Raster (Project Raster) (management)
    Projected_DEM = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Projected_DEM"
    arcpy.management.ProjectRaster(in_raster=DEM, out_raster=Projected_DEM, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", cell_size="10 10")
    Projected_DEM = arcpy.Raster(Projected_DEM)

    # Process: Aspect (Aspect) (sa)
    Aspect_2_ = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Aspect"
    Aspect = Aspect_2_
    Aspect_2_ = arcpy.sa.Aspect(Projected_DEM, "PLANAR", "METER", "GEODESIC_AZIMUTHS", "GPU_THEN_CPU")
    Aspect_2_.save(Aspect)


    # Process: Reclassify (2) (Reclassify) (sa)
    Reclass_Aspect = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_Aspect"
    Reclassify_2_ = Reclass_Aspect
    Reclass_Aspect = arcpy.sa.Reclassify(Aspect_2_, "VALUE", "-1 90 1;90 120 2;120 140 3;140 170 4;170 190 5;190 210 4;210 240 3;240 270 2;270 360 1", "DATA")
    Reclass_Aspect.save(Reclassify_2_)


    # Process: Slope (Slope) (sa)
    Slope_2_ = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Slope"
    Slope = Slope_2_
    Slope_2_ = arcpy.sa.Slope(Projected_DEM, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
    Slope_2_.save(Slope)


    # Process: Reclassify (3) (Reclassify) (sa)
    Reclass_Slope = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_Slope"
    Reclassify_3_ = Reclass_Slope
    Reclass_Slope = arcpy.sa.Reclassify(Slope_2_, "VALUE", "0 3 5;3 6 4;6 10 3;10 15 2;15 100 1", "DATA")
    Reclass_Slope.save(Reclassify_3_)


    # Process: Clip Raster (4) (Clip Raster) (management)
    LandCover_Clip = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\LandCover_Clip"
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
        arcpy.management.Clip(in_raster=LandCover_tif, rectangle="1010408.87982776 1171210.41118817 1194800.55151863 1399594.66982113", out_raster=LandCover_Clip, in_template_dataset=study_area, clipping_geometry="ClippingGeometry")
        LandCover_Clip = arcpy.Raster(LandCover_Clip)

    # Process: Project Raster (3) (Project Raster) (management)
    Projected_Landcover = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Projected_Landcover"
    arcpy.management.ProjectRaster(in_raster=LandCover_Clip, out_raster=Projected_Landcover, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", cell_size="10 10")
    Projected_Landcover = arcpy.Raster(Projected_Landcover)

    # Process: Reclassify (4) (Reclassify) (sa)
    Reclass_Landcover = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_Landcover"
    Reclassify_4_ = Reclass_Landcover
    Reclass_Landcover = arcpy.sa.Reclassify(Projected_Landcover, "Value", "0 1;10 1;20 4;30 2;40 3;50 1;60 5;80 1;90 1", "DATA")
    Reclass_Landcover.save(Reclassify_4_)


    # Process: Reclassify (7) (Reclassify) (sa)
    Reclass_DEM = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_DEM"
    Reclassify_7_ = Reclass_DEM
    Reclass_DEM = arcpy.sa.Reclassify(Projected_DEM, "Value", "389 443 1;443 479 2;479 526 3;526 573 4;573 1231 5", "DATA")
    Reclass_DEM.save(Reclassify_7_)


    # Process: Clip Raster (3) (Clip Raster) (management)
    Gird_Proximity_Clip = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Gird_Proximity_Clip"
    arcpy.management.Clip(in_raster=Gird_Proximity, rectangle="1010408.87982776 1171210.41118817 1194800.55151863 1399594.66982113", out_raster=Gird_Proximity_Clip, in_template_dataset=study_area, clipping_geometry="ClippingGeometry")
    Gird_Proximity_Clip = arcpy.Raster(Gird_Proximity_Clip)

    # Process: Reclassify (6) (Reclassify) (sa)
    Reclass_Grid = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_Grid"
    Reclassify_6_ = Reclass_Grid
    Reclass_Grid = arcpy.sa.Reclassify(Gird_Proximity_Clip, "VALUE", "0 919.257966 5;919.257966 2413.052160 4;2413.052160 4481.382583 3;4481.382583 7813.692708 2;7813.692708 29301.347656 1", "DATA")
    Reclass_Grid.save(Reclassify_6_)


    # Process: Clip Raster (5) (Clip Raster) (management)
    Proximity_Road_Clip = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Proximity_Road_Clip"
    arcpy.management.Clip(in_raster=Road_Proximity, rectangle="1010408.87982776 1171210.41118817 1194800.55151863 1399594.66982113", out_raster=Proximity_Road_Clip, in_template_dataset=study_area, clipping_geometry="ClippingGeometry")
    Proximity_Road_Clip = arcpy.Raster(Proximity_Road_Clip)

    # Process: Reclassify (5) (Reclassify) (sa)
    Reclass_Road = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Reclass_Road"
    Reclassify_5_ = Reclass_Road
    Reclass_Road = arcpy.sa.Reclassify(Proximity_Road_Clip, "VALUE", "0 584.461277 5;584.461277 811.761307 4;811.761307 1396.222584 3;1396.222584 2899.059979 2;2899.059979 6763.336914 5", "DATA")
    Reclass_Road.save(Reclassify_5_)


    # Process: Weighted Overlay (Weighted Overlay) (sa)
    Weighted = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Weighted"
    Weighted_Overlay = Weighted
    Weighted = arcpy.sa.WeightedOverlay(WOTable([[Reclass_SolarPV, 36 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])], [Reclass_Aspect, 14 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])], [Reclass_Slope, 8 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])], [Reclass_Landcover, 5 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])], [Reclass_DEM, 5 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])], [Reclass_Grid, 16 , 'Value' , RemapValue([[1, 1], [2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])], [Reclass_Road, 16 , 'Value' , RemapValue([[2, 2], [3, 3], [4, 4], [5, 6], ['NODATA', 'NODATA']])]], [1, 10, 1]))
    Weighted.save(Weighted_Overlay)


    # Process: Reclassify (8) (Reclassify) (sa)
    Weighted_Reclass = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Weighted_Reclass"
    Reclassify_8_ = Weighted_Reclass
    Weighted_Reclass = arcpy.sa.Reclassify(Weighted, "VALUE", "1 3 1;3 4 2;4 6 3", "DATA")
    Weighted_Reclass.save(Reclassify_8_)


    # Process: Extract by Mask (Extract by Mask) (sa)
    Suitable_Solar_Farm = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\Suitable_Solar_Farm"
    Extract_by_Mask = Suitable_Solar_Farm
    Suitable_Solar_Farm = arcpy.sa.ExtractByMask(Weighted_Reclass, protectedarea, "OUTSIDE", "1024518.4582528 1177204.2314528 1193977.03222683 1398013.88844926 PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")
    Suitable_Solar_Farm.save(Extract_by_Mask)


    # Process: Project Raster (4) (Project Raster) (management)
    SuitableLocations = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\SuitableLocations"
    arcpy.management.ProjectRaster(in_raster=Suitable_Solar_Farm, out_raster=SuitableLocations, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_31N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",3.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", cell_size="5 5")
    SuitableLocations = arcpy.Raster(SuitableLocations)

    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    SuitableLocationsforFarm = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\SuitableLocationsforFarm"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=SuitableLocations, out_polygon_features=SuitableLocationsforFarm)

    # Process: Pairwise Dissolve (Pairwise Dissolve) (analysis)
    SuitableLocationsFarm = "C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb\\SuitableLocationsFarm"
    arcpy.analysis.PairwiseDissolve(in_features=SuitableLocationsforFarm, out_feature_class=SuitableLocationsFarm, dissolve_field=["GRIDCODE"])

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb", workspace="C:\\Users\\DELL\\Downloads\\SolarPowr Suitability\\Solar Farm Suitability Analysis\\Solar Farm Suitability Analysis.gdb"):
        MSolarFarmSuitability()
